Scroll snap
Developer-DAO/code-claim-site pull request #30
Opened 2022-01-29 19:45 UTC by andreivdev

### What does it do?

Adds scroll snap and scroll arrows

### Any helpful background information?

No

### Any new dependencies? Why were they added?

No

### Relevant screenshots/gifs

<img width="544" alt="Screenshot 2022-01-29 at 21 43 21" src="https://user-images.githubusercontent.com/8058187/151675334-3567caf7-25b4-4c09-ba69-1184fb90dd2e.png">
<img width="544" alt="Screenshot 2022-01-29 at 21 43 15" src="https://user-images.githubusercontent.com/8058187/151675336-06e4a010-fc55-461a-a7bd-a3b9aedee3ff.png">

### Does it close any issues?

Closes #15

2022-02-01 02:29 UTC, janndriessen requested changes
Good start. In Chrome (mobile view) it seems to work but there is a few things I found.

* The arrows are interfering with the content pushing it down/up e.g. the claim card should always be vertically centered (probably check for absolute positioning)
* Didn't have time to test with a real phone but on an iOS simulator the site completely broke (might not be just due to the changes here). 
* Some minor comments in code

2022-02-01 02:29 UTC, janndriessen commented on packages/next-app/src/pages/index.tsx
> +                {!isWeb && (
For conditions I prefer the _happy path_ so why not use `isMobile` here?

Also, shouldn't the `<Center>` be inside the condition?

2022-02-01 02:29 UTC, janndriessen commented on packages/next-app/src/pages/index.tsx
> +            {!isWeb && (
same as below

2022-02-01 02:29 UTC, janndriessen commented on packages/next-app/src/pages/index.tsx
> +  const isWeb = breakpointValue === sm;
here you could change to `isMobile`

2022-02-01 07:23 UTC, andreivdev commented on packages/next-app/src/pages/index.tsx
> +                {!isWeb && (
I used isWeb for consistency with [the logo file](https://github.com/Developer-DAO/code-claim-site/blob/main/packages/next-app/src/components/Logo.tsx#L4).

I'm not sure if Center can be inside the condition, because that flexbox needs to grow both on mobile and web to keep the card vertically centered.

2022-02-01 08:48 UTC, andreivdev commented
Updated with:
- isMobile instead of isWeb
- Center inside condition
- Vertically centred components. 


Small mobile:

<img width="530" alt="Screenshot 2022-02-01 at 10 43 09" src="https://user-images.githubusercontent.com/8058187/151937631-47bb7d7e-57eb-4bb3-9363-10a051b92256.png">
<img width="530" alt="Screenshot 2022-02-01 at 10 43 03" src="https://user-images.githubusercontent.com/8058187/151937638-522d4c54-4d4f-4181-aacd-d62b624a1c20.png">

Large mobile:

<img width="552" alt="Screenshot 2022-02-01 at 10 43 33" src="https://user-images.githubusercontent.com/8058187/151937681-dbea6632-42c7-4daa-8f4d-11128347f9d2.png">
<img width="552" alt="Screenshot 2022-02-01 at 10 43 42" src="https://user-images.githubusercontent.com/8058187/151937689-d4516f5f-eb82-4303-a350-d21c48cd589c.png">

Web:

<img width="1531" alt="Screenshot 2022-02-01 at 10 44 02" src="https://user-images.githubusercontent.com/8058187/151937703-a5851f11-7485-4175-a0cc-525c2e5c7939.png">

2022-02-03 18:30 UTC, janndriessen commented
<img width="1440" alt="web" src="https://user-images.githubusercontent.com/2104965/152405929-a67b7c36-c90a-4d40-b7bb-f27d7ac48c28.png">

Not sure if I running it wrong but I currently get this for web. On mobile the card is pushed to the bottom as well. Did you push all changes?

2022-02-03 19:13 UTC, andreivdev commented
You're right. 

My browser must have been caching something.

2022-02-05 13:26 UTC, janndriessen commented on packages/next-app/src/pages/index.tsx
> +  const isMobile = useBreakpointValue({ base: true, lg: false });
nice!

2022-02-05 13:27 UTC, janndriessen approved these changes
LGTM! good clean up too. 🌟 🚢 it.

2022-02-05 13:27 UTC, merged