Tests for MerkleProof.sol #2
Developer-DAO/code-claim-site pull request #57
Opened 2022-02-20 14:24 UTC by IoanDraghici

### What does it do?
Tests for the MerkleProof.sol library.

### Any helpful background information?
None

### Any new dependencies? Why were they added?
None

### Relevant screenshots/gifs

### Does it close any issues?

Closes #2

2022-02-20 18:03 UTC, janndriessen commented
I'll take a closer look tomorrow or the day after. @IoanDraghici please run prettier on your files in the meanwhile - as the building process found some issues.

2022-03-13 17:36 UTC, janndriessen requested changes

2022-03-13 17:36 UTC, janndriessen commented on packages/hardhat/test/MerkleProof.test.ts
> +    it('returns true and index 1 for a valid Merkle proof', async function () {
`returns true and index 1` should say `returns true and index 2`. The expect expression is also actually testing for `2`.

2022-03-13 17:51 UTC, janndriessen commented
When the comment is fixed, @embiem can review as well or merge right away.

2022-03-13 21:10 UTC, IoanDraghici commented on packages/hardhat/test/MerkleProof.test.ts
> +    it('returns true and index 1 for a valid Merkle proof', async function () {
fixed

2022-03-14 06:49 UTC, janndriessen approved these changes
🚀

2022-03-19 12:35 UTC, merged